### ISSUE TITLE
Creating JSON for a CSV without logging into environment

### ISSUE THREAD

**Issue by JohnnyCosgrove** [forcedotcom/Analytics-Cloud-Dataset-Utils#2]
Hi guys, awesome utility, but I note that version 3 had a function which the new version 8 doesn't seem to still have? Version 3 was able to quickly create a JSON file in your local directory based on the target CSV. Version 8 appears to take me straight to the web utility, which will just attempt an upload. Am I missing something? The JSON creation by itself is really useful.

**Comment by datasetutil** [comment]
the JSON is just a by product. What the users is really trying to do is upload the file to analytic s cloud. that's why we took the interim action out. If you use the load action it will still produce the json for you and also upload the file for you. Also, the credentials are now mandatory and a way for to make sure only people with access to Analytics cloud are using the utility.

**Comment by JohnnyCosgrove** [comment]
Thanks guys, understand. Completely agree with the need to authenticate the tool. The usecase for the JSON generation was purely troubleshooting. It was great to have an SFDC JSON generator, so if I'm hitting issues with a data upload, I can cross check my JSON settings to see if that's a factor. So, I think it would still be useful to have the option to export it locally, but I understand it's probably not a priority.

**Comment by datasetutil** [comment]
the json is still being generated and stored locally exactly as before. just use the upload action.
